version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Testing the Python code...
      - python HelloWorld_test.py
  post_build:
    commands:
      - echo Build completed on `date`